import type { Province } from '../types'

export const OFFICIAL_PROVINCES: Province[] = [
  { id: 2, name: 'ALBACETE', ccaaId: 7, ccaaName: 'Castilla la Mancha' },
  { id: 3, name: 'ALICANTE', ccaaId: 10, ccaaName: 'Comunidad Valenciana' },
  { id: 4, name: 'ALMERÍA', ccaaId: 1, ccaaName: 'Andalucia' },
  { id: 1, name: 'ARABA/ÁLAVA', ccaaId: 16, ccaaName: 'País Vasco' },
  { id: 33, name: 'ASTURIAS', ccaaId: 3, ccaaName: 'Asturias' },
  { id: 5, name: 'ÁVILA', ccaaId: 8, ccaaName: 'Castilla y León' },
  { id: 6, name: 'BADAJOZ', ccaaId: 11, ccaaName: 'Extremadura' },
  { id: 7, name: 'BALEARS (ILLES)', ccaaId: 4, ccaaName: 'Baleares' },
  { id: 8, name: 'BARCELONA', ccaaId: 9, ccaaName: 'Cataluña' },
  { id: 48, name: 'BIZKAIA', ccaaId: 16, ccaaName: 'País Vasco' },
  { id: 9, name: 'BURGOS', ccaaId: 8, ccaaName: 'Castilla y León' },
  { id: 10, name: 'CÁCERES', ccaaId: 11, ccaaName: 'Extremadura' },
  { id: 11, name: 'CÁDIZ', ccaaId: 1, ccaaName: 'Andalucia' },
  { id: 39, name: 'CANTABRIA', ccaaId: 6, ccaaName: 'Cantabria' },
  { id: 12, name: 'CASTELLÓN / CASTELLÓ', ccaaId: 10, ccaaName: 'Comunidad Valenciana' },
  { id: 51, name: 'CEUTA', ccaaId: 18, ccaaName: 'Ceuta' },
  { id: 13, name: 'CIUDAD REAL', ccaaId: 7, ccaaName: 'Castilla la Mancha' },
  { id: 14, name: 'CÓRDOBA', ccaaId: 1, ccaaName: 'Andalucia' },
  { id: 15, name: 'CORUÑA (A)', ccaaId: 12, ccaaName: 'Galicia' },
  { id: 16, name: 'CUENCA', ccaaId: 7, ccaaName: 'Castilla la Mancha' },
  { id: 20, name: 'GIPUZKOA', ccaaId: 16, ccaaName: 'País Vasco' },
  { id: 17, name: 'GIRONA', ccaaId: 9, ccaaName: 'Cataluña' },
  { id: 18, name: 'GRANADA', ccaaId: 1, ccaaName: 'Andalucia' },
  { id: 19, name: 'GUADALAJARA', ccaaId: 7, ccaaName: 'Castilla la Mancha' },
  { id: 21, name: 'HUELVA', ccaaId: 1, ccaaName: 'Andalucia' },
  { id: 22, name: 'HUESCA', ccaaId: 2, ccaaName: 'Aragón' },
  { id: 23, name: 'JAÉN', ccaaId: 1, ccaaName: 'Andalucia' },
  { id: 24, name: 'LEÓN', ccaaId: 8, ccaaName: 'Castilla y León' },
  { id: 25, name: 'LLEIDA', ccaaId: 9, ccaaName: 'Cataluña' },
  { id: 27, name: 'LUGO', ccaaId: 12, ccaaName: 'Galicia' },
  { id: 28, name: 'MADRID', ccaaId: 13, ccaaName: 'Madrid' },
  { id: 29, name: 'MÁLAGA', ccaaId: 1, ccaaName: 'Andalucia' },
  { id: 52, name: 'MELILLA', ccaaId: 19, ccaaName: 'Melilla' },
  { id: 30, name: 'MURCIA', ccaaId: 14, ccaaName: 'Murcia' },
  { id: 31, name: 'NAVARRA', ccaaId: 15, ccaaName: 'Navarra' },
  { id: 32, name: 'OURENSE', ccaaId: 12, ccaaName: 'Galicia' },
  { id: 34, name: 'PALENCIA', ccaaId: 8, ccaaName: 'Castilla y León' },
  { id: 35, name: 'PALMAS (LAS)', ccaaId: 5, ccaaName: 'Canarias' },
  { id: 36, name: 'PONTEVEDRA', ccaaId: 12, ccaaName: 'Galicia' },
  { id: 26, name: 'RIOJA (LA)', ccaaId: 17, ccaaName: 'Rioja (La)' },
  { id: 37, name: 'SALAMANCA', ccaaId: 8, ccaaName: 'Castilla y León' },
  { id: 38, name: 'SANTA CRUZ DE TENERIFE', ccaaId: 5, ccaaName: 'Canarias' },
  { id: 40, name: 'SEGOVIA', ccaaId: 8, ccaaName: 'Castilla y León' },
  { id: 41, name: 'SEVILLA', ccaaId: 1, ccaaName: 'Andalucia' },
  { id: 42, name: 'SORIA', ccaaId: 8, ccaaName: 'Castilla y León' },
  { id: 43, name: 'TARRAGONA', ccaaId: 9, ccaaName: 'Cataluña' },
  { id: 44, name: 'TERUEL', ccaaId: 2, ccaaName: 'Aragón' },
  { id: 45, name: 'TOLEDO', ccaaId: 7, ccaaName: 'Castilla la Mancha' },
  { id: 46, name: 'VALENCIA / VALÈNCIA', ccaaId: 10, ccaaName: 'Comunidad Valenciana' },
  { id: 47, name: 'VALLADOLID', ccaaId: 8, ccaaName: 'Castilla y León' },
  { id: 49, name: 'ZAMORA', ccaaId: 8, ccaaName: 'Castilla y León' },
  { id: 50, name: 'ZARAGOZA', ccaaId: 2, ccaaName: 'Aragón' },
]
